[tool.poetry]
name = "local-newsifier"
version = "0.1.0"
description = "A robust system for fetching, analyzing, and storing local news articles from Gainesville, FL"
authors = ["Alex Rockwell"]
readme = "README.md"
packages = [{include = "local_newsifier", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
crewai = "^0.114.0"
pydantic = "^2.11.3"
spacy = "^3.8.5"
requests = "^2.32.3"
beautifulsoup4 = "^4.13.3"
tenacity = "^9.1.2"
selenium = "^4.31.0"
webdriver-manager = "^4.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
