from pathlib import Path
import re, textwrap

TABLE_RE = re.compile(r"class (\w+)\(([^)]*),? *table *= *True[)]:")

for line in Path('/tmp/table_models.txt').read_text().splitlines():
    path, lineno, _ = line.split(':', maxsplit=2)
    file = Path(path)
    src = file.read_text()
    match = TABLE_RE.search(src)
    if not match:
        continue
    name, bases = match.groups()
    base_name = f"{name}Base"
    read_name = f"{name}Read"
    if base_name in src:
        continue
    src = src.replace(
        f"class {name}(",
        textwrap.dedent(f"""
        class {base_name}(SQLModel):
            \"\"\"Shared fields for {name}. Autogenerated by split_models.py\"\"\"
            # TODO: move field defs here
        class {name}(
        """).lstrip()
    )
    append_block = textwrap.dedent(f"""
        class {read_name}({base_name}):
            \"\"\"Read-only DTO detached from session\"\"\"
            id: int
    """)
    insert_at = src.rfind('class')
    src = src[:insert_at] + append_block + src[insert_at:]
    file.write_text(src)
